TOP = ../..
include $(TOP)/configure/CONFIG
#ARCH = linux-x86_64-ub18
ARCH = linux-x86_64
#ARCH = windows-x64-static-vs2017
#ARCH = windows-x64-static
TARGETS = envPaths
include $(TOP)/configure/RULES.ioc
